<a href="https://colab.research.google.com/github/raagKush/ML_learning_google_collab/blob/main/torch_torchvision_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install torch torchvision

In [ ]:
import torch
tensor = torch.tensor([2,3,53,62,])
print(tensor)

tensor([ 2,  3, 53, 62])


In [ ]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
tensor_on_device = torch.rand((3,4)).to(device)
print(tensor_on_device)

tensor([[0.4051, 0.4912, 0.7498, 0.0257],
        [0.9055, 0.2969, 0.0425, 0.1939],
        [0.9856, 0.5981, 0.9109, 0.0026]], device='cuda:0')


In [ ]:
tensor_a = torch.randn(2, 3)
tensor_b = torch.randn(3, 2)
result = torch.matmul(tensor_a, tensor_b)
print(result)

tensor([[-0.2721, -0.3140],
        [ 0.9543, -0.9644]])


In [ ]:
tensor_a = torch.randn(3, 3)
tensor_b = torch.randn(3, 3)
result = tensor_a*tensor_b
print(tensor_a,tensor_b,result)

tensor([[-1.6072, -0.1309,  0.3279],
        [ 0.1446, -0.2797, -0.0430],
        [ 0.9806,  0.2089,  0.0611]]) tensor([[-0.9341, -3.1530,  0.6879],
        [-1.7407,  0.7094,  2.3871],
        [ 0.0521, -2.0146, -0.1426]]) tensor([[ 1.5013,  0.4128,  0.2256],
        [-0.2518, -0.1984, -0.1028],
        [ 0.0511, -0.4209, -0.0087]])


In [7]:
import time

# Create a tensor on CPU
tensor_a_cpu = torch.randn(10000, 10000)
tensor_b_cpu = torch.randn(10000, 10000)

# Measure time on CPU
start = time.time()
result_cpu = torch.matmul(tensor_a_cpu, tensor_b_cpu)
time_CPU = time.time() - start
print(f"Time on CPU: {time_CPU} seconds")

# Move to GPU
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
tensor_a_gpu = tensor_a_cpu.to(device)
tensor_b_gpu = tensor_b_cpu.to(device)

# Measure time on GPU
start = time.time()
result_gpu = torch.matmul(tensor_a_gpu, tensor_b_gpu)
time_GPU = time.time() - start
print(f"Time on GPU: {time_GPU} seconds")
print(f"GPU is {(time_CPU/time_GPU):.2f} times faster" )


Time on CPU: 24.508305549621582 seconds
Time on GPU: 0.023717164993286133 seconds
GPU is 1033.36 times faster
